config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  resource :registration, only: %i[new create]
  resources :users, only: %i[show]
  resources :books, only: %i[index show] do
    member do
      post "borrow"
      patch "return_borrowed_book"
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "books#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :borrowings
  has_many :users, through: :borrowings

  validates :author, presence: true
  validates :title, presence: true
  validates :isbn, presence: true, uniqueness: true
  validates :status, presence: true

  enum :status, [ :available, :borrowed ]
end

app/models/borrowing.rb
class Borrowing < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :user_id, :book_id, :borrowed_at, :due_date, presence: true
  validates :book, uniqueness: { scope: :returned_at, message: "is already borrowed" }
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy
  has_many :borrowings
  has_many :books, through: :borrowings

  has_one_attached :avatar

  validates :email_address, presence: true, uniqueness: true
  validates :password, presence: true, on: :create
  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[show borrow return_borrowed_book]
  def index
    @books = Book.all
  end

  def show; end

  def borrow
    if @book.available?
      @borrowing = @book.borrowings.new(borrowed_at: Date.today, due_date: 2.weeks.from_now)
      @borrowing.user = Current.user

      if @borrowing.save
        @book.update(status: :borrowed)
        redirect_to @book, notice: "Book successfully borrowed!"
      else
        redirect_to @book, alert: "There was an issue with borrowing the book. Please try again."
      end
    else
      redirect_to @book, alert: "This book is currently unavailable."
    end
  end

  def return_borrowed_book
    @borrowed_book = Current.user.borrowings.find_by(book: @book, returned_at: nil)

    if @borrowed_book
      @borrowed_book.update(returned_at: Date.today)
      @book.update(status: :available)
      redirect_to user_path(Current.user), notice: "Book successfully returned!"
    else
      redirect_to user_path(Current.user), alert: "You have not borrowed this book."
    end
  end

  private
  def set_book
    @book = Book.find(params[:id])
  end
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
    end

    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end

    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  allow_unauthenticated_access

  layout "authentication"

  def new
    @user = User.new
  end

  def create
    @user = User.new(sign_up_params)
    if @user.save
      start_new_session_for @user
      redirect_to after_authentication_url, notice: "User registration successfull"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
  def sign_up_params
    params.expect(user: [ :avatar, :username, :email_address, :bio, :password, :password_confirmation ])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  layout "authentication"

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show]
  def show
    @borrowed_books = @user.books.includes(:borrowings).where(status: :borrowed)
  end

  private
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<div class="w-full border border-b-0 last:border border-gray-300 p-3 flex items-center justify-between">
  <div>
      <span>
        <%= link_to book.title, book_path(book), class: "text-blue-500" %> 
        <strong>By</strong>
      </span>
      <span><%= book.author%></span>
  </div>
  <div class="<%= book.available? ? 'bg-green-500': 'bg-red-500'%> px-4 rounded-md text-white">
    <%= book.status %>
  </div>
</div>

app/views/books/index.html.erb
<div class="w-full h-screen">
  <h1 class="font-bold text-4xl mb-6 underline underline-offset-8">Books</h1>
  <div>
    <%= render @books %>
  </div>
</div>

app/views/books/show.html.erb
<div class="mx-auto w-full">
  <% if alert = flash[:alert] %>
  <p class="py-2 px-3 bg-red-50 mb-5 text-red-500 font-medium rounded-lg inline-block" id="alert"><%= alert %></p>
  <% end %>

  <% if notice = flash[:notice] %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
  <div class="border border-gray-300 rounded-lg p-8 mb-6 shadow-lg hover:shadow-2xl transition-shadow duration-300 bg-white flex items-center justify-between">
    <div>
      <h2><%= @book.title %></h2>
      <p><%= @book.author%></p>
    </div>
    <% if @book.status == 'available' %>
        <%= link_to 'borrow', 
          borrow_book_path(@book),
          data: {turbo_method: :post },
          class: "bg-blue-500 text-white text-sm rounded-md py-1 px-4 hover:bg-blue-700" %>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<header class="bg-slate-500 text-white p-4 mb-6">
  <nav>
    <div class="flex items-center justify-between">
      <div>
          <%= link_to "Bookstore", root_path%>
      </div>
      <ul class="flex items-center gap-2">
        <% if Current.user %>
          <li>
            <%= link_to "Profile", user_path(Current.user) %>
          </li>
          <li>
            <%= button_to "Sign out", session_path, method: :delete, class: "cursor-pointer" %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Bookstore Library" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container p-6">
      <%= render "layouts/navbar" %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/authentication.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Authentication" %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
</head>
<body>
  <div class="container w-full h-screen flex items-center justify-center p-6">
    <%= yield %>
  </div>
</body>
</html>

app/views/shared/_errors.html.erb
<% if resource.errors.any? %>
  <div data-turbo-cache="false" class="text-red-500">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
        count: resource.errors.count,
        resource: resource.class.model_name.human.downcase
      )%>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/show.html.erb
<div>
  <div class="border border-gray-300 rounded-lg p-8 mb-6 shadow-lg hover:shadow-2xl transition-shadow duration-300 bg-white">
    <div class="flex items-center space-x-4">
      <% if @user.avatar.attached? %>
      <div>
        <%= image_tag @user.avatar, class: "w-32 h-32 rounded-full object-cover shadow-md" %>
      </div>
      <% end %>
      <div>
      <h2 class="text-xl font-semibold text-gray-800"><%= @user.username %></h2>
      <p class="text-gray-600 text-sm mt-2 lg:max-w-1/2"><%= @user.bio %></p>
      </div>
    </div>
  </div>

  <div>
    <p class="text-4xl mb-6 underline underline-offset-8">
      List of all books currently borrowed
    </p>
    <div>
      <% @borrowed_books.each do |book| %>
        <div class="w-full border border-b-0 last:border border-gray-300 p-3 flex items-center justify-between">
          <div>
            <span class="text-blue-500">
              <%= book.title %>
            </span>
            <strong>By</strong>
            <span><%= book.author%></span>
          </div>
          <div>
            <%= link_to 'return', 
              return_borrowed_book_book_path(book),
              data: {turbo_method: :patch },
              class:"bg-red-500 text-sm text-white rounded-md py-1 px-4 hover:bg-red-700" %>
          </div>
        </div>
      <% end %>
    </div>
</div>
</div>